# Generated by Django 2.2.10 on 2021-02-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotebox',
            name='background_color',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotebox',
            name='text_color',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
