# Generated by Django 2.2.10 on 2021-02-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20210223_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotebox',
            name='height',
            field=models.PositiveSmallIntegerField(default=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotebox',
            name='width',
            field=models.PositiveSmallIntegerField(default=620),
            preserve_default=False,
        ),
    ]
